# Generated by Django 6.0.4 on 2026-04-19 09:50

import django.db.models.deletion
import documents.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Original filename', max_length=255)),
                ('file', models.FileField(upload_to=documents.models.document_upload_path)),
                ('category', models.CharField(choices=[('arch_drawings', 'Architectural Drawings'), ('struct_drawings', 'Structural Drawings'), ('mep_drawings', 'MEP Drawings'), ('boq', 'BOQ / Estimates'), ('contracts', 'Contracts'), ('permits', 'Permits & Approvals'), ('site_reports', 'Site Reports'), ('other', 'Other')], default='other', max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('file_size', models.PositiveIntegerField(default=0, help_text='Bytes')),
                ('validation_status', models.CharField(choices=[('pending', 'Pending Review'), ('validated', 'Validated'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('rejection_reason', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='projects.project')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
