export enum GraphNodeType {
  PROJECT = "PROJECT",
  CREDIT = "CREDIT",
  REQUIREMENT = "REQUIREMENT",
  ASSIGNMENT = "ASSIGNMENT",
  DOCUMENT = "DOCUMENT",
  CONTRIBUTOR = "CONTRIBUTOR",
  RISK = "RISK",
  DECISION = "DECISION",
  REVIEW = "REVIEW",
  SUBMISSION = "SUBMISSION",
  CERTIFICATION = "CERTIFICATION",
  WORKLOAD = "WORKLOAD",
  PRIORITY_ACTION = "PRIORITY_ACTION"
}
