export enum GraphRelationship {
  REQUIRES = "REQUIRES",
  SATISFIES = "SATISFIES",
  ASSIGNED_TO = "ASSIGNED_TO",
  BLOCKS = "BLOCKS",
  DEPENDS_ON = "DEPENDS_ON",
  SUPPORTS = "SUPPORTS",
  CONTRIBUTES_TO = "CONTRIBUTES_TO",
  APPROVED_BY = "APPROVED_BY",
  CREATED_BY = "CREATED_BY",
  AFFECTS_CERTIFICATION = "AFFECTS_CERTIFICATION",
  REDUCES_RISK = "REDUCES_RISK",
  IMPROVES_READINESS = "IMPROVES_READINESS"
}
