-- Tracks persistent memory across the project lifecycle for Harita to reference
CREATE TABLE IF NOT EXISTS ai_memory (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    project_id UUID NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    entity_type TEXT NOT NULL, -- e.g., 'credit', 'submittal', 'clarification', 'document'
    entity_id UUID, -- Optional direct reference to the entity
    context_data JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Event stream to rebuild or track memory context state changes
CREATE TABLE IF NOT EXISTS ai_memory_events (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    project_id UUID NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    ai_memory_id UUID REFERENCES ai_memory(id) ON DELETE SET NULL,
    event_type TEXT NOT NULL,
    event_data JSONB NOT NULL DEFAULT '{}'::jsonb,
    actor_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Stores chat conversation context linked to the project and user
CREATE TABLE IF NOT EXISTS conversation_context (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    project_id UUID NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    session_id TEXT NOT NULL,
    messages JSONB NOT NULL DEFAULT '[]'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Stores recommendations generated by the recommendation engine
CREATE TABLE IF NOT EXISTS ai_recommendations (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    project_id UUID NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    credit_id UUID REFERENCES project_credits(id) ON DELETE CASCADE,
    recommendation_type TEXT NOT NULL, -- e.g., 'missing_evidence', 'next_action', 'reuse'
    recommendation_details JSONB NOT NULL DEFAULT '{}'::jsonb,
    impact_score NUMERIC,
    confidence NUMERIC,
    is_active BOOLEAN NOT NULL DEFAULT true,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Tracking plans for resolving clarifications
CREATE TABLE IF NOT EXISTS clarification_intelligence (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    project_id UUID NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    document_id UUID REFERENCES project_document(id) ON DELETE CASCADE,
    parsed_intent JSONB NOT NULL DEFAULT '{}'::jsonb,
    resolution_plan JSONB NOT NULL DEFAULT '{}'::jsonb,
    status TEXT NOT NULL DEFAULT 'PENDING',
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Tracks structured extractions from documents
CREATE TABLE IF NOT EXISTS evidence_extractions (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    project_id UUID NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    document_id UUID NOT NULL REFERENCES project_document(id) ON DELETE CASCADE,
    extraction_type TEXT NOT NULL, -- e.g., 'water_flow', 'energy_capacity', 'architecture_stats'
    extracted_data JSONB NOT NULL DEFAULT '{}'::jsonb,
    confidence NUMERIC NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Stores KPIs and telemetry for the AI features
CREATE TABLE IF NOT EXISTS ai_metrics (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    project_id UUID REFERENCES projects(id) ON DELETE CASCADE,
    metric_name TEXT NOT NULL,
    metric_value NUMERIC NOT NULL,
    context_data JSONB DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Enable RLS
ALTER TABLE ai_memory ENABLE ROW LEVEL SECURITY;
ALTER TABLE ai_memory_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE conversation_context ENABLE ROW LEVEL SECURITY;
ALTER TABLE ai_recommendations ENABLE ROW LEVEL SECURITY;
ALTER TABLE clarification_intelligence ENABLE ROW LEVEL SECURITY;
ALTER TABLE evidence_extractions ENABLE ROW LEVEL SECURITY;
ALTER TABLE ai_metrics ENABLE ROW LEVEL SECURITY;

-- Standard Project Scope Policies
CREATE POLICY "Project team can view ai_memory"
    ON ai_memory FOR SELECT
    USING (project_id IN (SELECT project_id FROM project_users WHERE user_id = auth.uid()));

CREATE POLICY "Project team can view ai_memory_events"
    ON ai_memory_events FOR SELECT
    USING (project_id IN (SELECT project_id FROM project_users WHERE user_id = auth.uid()));

CREATE POLICY "Users can manage their conversation_context"
    ON conversation_context FOR ALL
    USING (user_id = auth.uid());

CREATE POLICY "Project team can view ai_recommendations"
    ON ai_recommendations FOR SELECT
    USING (project_id IN (SELECT project_id FROM project_users WHERE user_id = auth.uid()));

CREATE POLICY "Project team can view clarification_intelligence"
    ON clarification_intelligence FOR SELECT
    USING (project_id IN (SELECT project_id FROM project_users WHERE user_id = auth.uid()));

CREATE POLICY "Project team can view evidence_extractions"
    ON evidence_extractions FOR SELECT
    USING (project_id IN (SELECT project_id FROM project_users WHERE user_id = auth.uid()));

CREATE POLICY "Admins can view ai_metrics"
    ON ai_metrics FOR SELECT
    USING (true); -- Usually restricted, keeping open for MVP tracking

-- Indexes
CREATE INDEX idx_ai_memory_project ON ai_memory(project_id);
CREATE INDEX idx_ai_recommendations_project_credit ON ai_recommendations(project_id, credit_id);
CREATE INDEX idx_evidence_extractions_document ON evidence_extractions(document_id);
CREATE INDEX idx_conversation_context_user_session ON conversation_context(user_id, session_id);
